-- Seed CIE-10 codes
INSERT INTO "cie10_codes" ("id", "code", "description", "category") VALUES
(gen_random_uuid(), 'M17.0', 'GONARTROSIS BILATERAL PRIMARIA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M17.1', 'OTRAS GONARTROSIS PRIMARIAS', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M17.2', 'GONARTROSIS BILATERAL SECUNDARIA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M17.3', 'OTRAS GONARTROSIS SECUNDARIAS', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M17.9', 'GONARTROSIS NO ESPECIFICADA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M16.0', 'COXARTROSIS BILATERAL PRIMARIA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M16.1', 'OTRAS COXARTROSIS PRIMARIAS', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M16.9', 'COXARTROSIS NO ESPECIFICADA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M54.4', 'LUMBAGO CON CIATICA', 'Trastornos de la columna vertebral'),
(gen_random_uuid(), 'M54.5', 'DOLOR LUMBAR BAJO', 'Trastornos de la columna vertebral'),
(gen_random_uuid(), 'M54.3', 'CIATICA', 'Trastornos de la columna vertebral'),
(gen_random_uuid(), 'M54.2', 'CERVICALGIA', 'Trastornos de la columna vertebral'),
(gen_random_uuid(), 'M54.1', 'RADICULOPATIA CERVICAL', 'Trastornos de la columna vertebral'),
(gen_random_uuid(), 'M54.0', 'RADICULOPATIA LUMBAR', 'Trastornos de la columna vertebral'),
(gen_random_uuid(), 'M65.2', 'TENDINITIS CALCIFICADA', 'Trastornos de los tejidos blandos'),
(gen_random_uuid(), 'M75.0', 'CAPSULITIS ADHESIVA DEL HOMBRO', 'Trastornos de los tejidos blandos'),
(gen_random_uuid(), 'M75.1', 'SINDROME DEL MANGITO DE LOS ROTADORES', 'Trastornos de los tejidos blandos'),
(gen_random_uuid(), 'M75.2', 'TENDINITIS DEL MANGITO DE LOS ROTADORES', 'Trastornos de los tejidos blandos'),
(gen_random_uuid(), 'M15.0', 'ARTROSIS GENERALIZADA PRIMARIA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M19.0', 'ARTROSIS PRIMARIA DE OTROS ARTICULACIONES', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M19.9', 'ARTROSIS NO ESPECIFICADA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M79.1', 'MIALGIA', 'Trastornos de los tejidos blandos'),
(gen_random_uuid(), 'M79.2', 'FIBROMIALGIA', 'Trastornos de los tejidos blandos'),
(gen_random_uuid(), 'M25.5', 'DOLOR ARTICULAR', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M81.0', 'OSTEOPOROSIS POLEMENOPAUSICA', 'Enfermedades óseas'),
(gen_random_uuid(), 'M81.9', 'OSTEOPOROSIS NO ESPECIFICADA', 'Enfermedades óseas'),
(gen_random_uuid(), 'M05.9', 'POLIARTRITIS REUMATOIDEA SEROPOSITIVA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'M06.9', 'POLIARTRITIS REUMATOIDEA NO ESPECIFICADA', 'Enfermedades osteoarticulares'),
(gen_random_uuid(), 'G56.0', 'SINDROME DEL TUNEL CARPIANO', 'Enfermedades del sistema nervioso'),
(gen_random_uuid(), 'G57.0', 'LESION DEL NERVIO CIATICO', 'Enfermedades del sistema nervioso'),
(gen_random_uuid(), 'S83.2', 'ROTURA DE MENISCO MEDIAL', 'Lesiones externas'),
(gen_random_uuid(), 'S93.4', 'ESGUINCE DEL TOBILLO', 'Lesiones externas')
ON CONFLICT ("code") DO NOTHING;
